services:

  app:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      dbserver:
        condition: service_healthy
        restart: true

  dbserver:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
#    ports:
#      - "5000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G